version: '3'

services:
  app:
    build: .
    image: moharamm/crud11
    container_name: persons_crud
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
networks:
  my-network:

volumes:
  data:
